spring:
  datasource:
    url: jdbc:mysql://localhost:3307/UMS
#    url: jdbc:mysql://localhost:3306/backendjavaspring
    username: root
#    password:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              create-target: "classpath:create-db.sql"

  application:
    name: SistemiMenaxhimitTeFakulltetit
